version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dss-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-dss_database}
    volumes:
      - dss_postgres_data:/var/lib/postgresql/data

  db-service:
    image: ydavidovici/dss-db-service:latest
    build:
      context: ./apps/db-service
      dockerfile: Dockerfile
    container_name: dss-db-service
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-dss_database}
    depends_on:
      - postgres

  auth-service:
    image: ydavidovici/dss-auth-service:latest
    build:
      context: ./apps/auth-service
      dockerfile: Dockerfile
    container_name: dss-auth-service
    depends_on:
      - db-service

volumes:
  dss_postgres_data: