/**
 * Signal type enum
 */
export type SignalType = 'buy' | 'sell' | 'hold';

/**
 * Trading signal generated by strategy
 */
export interface Signal {
  /** Trading symbol */
  symbol: string;

  /** Signal type: buy, sell, or hold */
  type: SignalType;

  /** Signal generation timestamp */
  timestamp: string;

  /** Strategy that generated signal */
  strategy: string;

  /** Signal strength/confidence (0-1) */
  strength?: number;

  /** Current price when signal generated */
  price: number;

  /** Indicator values that led to signal */
  indicators: {
    fastMA?: number;
    slowMA?: number;
    [key: string]: number | undefined;
  };

  /** Human-readable reason for signal */
  reason: string;

  /** Additional metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Signal log for database storage
 */
export interface SignalLog extends Signal {
  /** Unique identifier */
  id?: string;

  /** Whether signal was acted upon */
  executed?: boolean;

  /** Trade ID if executed */
  tradeId?: string;
}

/**
 * Signal generation result with context
 */
export interface SignalResult {
  signal: Signal;
  candles: Array<{ timestamp: Date; close: number }>;
  fastMA: number[];
  slowMA: number[];
}
