version: "3.8"

services:
  auth-service:
    build:
      context: ../apps/auth-service
    ports:
      - "5000:5000"
    env_file:
      - ../apps/auth-service/.env

  davidovici-frontend:
    build:
      context: ../apps/davidovici-frontend
    ports:
      - "3000:3000"
