version: "3.8"

services:
  auth-service:
    build:
      context: ../apps/auth
      dockerfile: Dockerfile
    env_file:
      - ../apps/auth/.env      # ← point to the real .env file
    expose:
      - "5000"
    networks:
      - web

  davidovici-frontend:
    build:
      context: ../apps/ds-frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    networks:
      - web

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - davidovici-frontend
    networks:
      - web

networks:
  web:
    driver: bridge
