version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"    # expose only HTTP
    volumes:
      # mount the static build output into nginx's html dir
      - ../apps/ds-frontend/public:/usr/share/nginx/html:ro
      # your custom nginx config
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
