version: "3.8"

# docker-compose.yml
services:
  davidovici-frontend:
    build:
      context: ../apps/ds-frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    networks:
      - web

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - davidovici-frontend
    networks:
      - web

networks:
  web:
    driver: bridge